---
- name: unload blacklisted modules
  modprobe: name={{item}} state=absent
  with_items: "{{blacklisted_modules}}"
  become: true

- name: unload disabled modules
  modprobe: name={{item}} state=absent
  with_items: "{{disabled_modules}}"
  become: true

- name: mkdir /etc/modprobe.d
  file: path=/etc/modprobe.d state=directory
  become: true

- name: create conf file
  template: src=modprobe.conf dest={{modules_file}}
  become: true
